num_classes: 4
classes:
    - Epilepsy
    - Walking
    - Running
    - Sawing
class_to_index:
  epilepsy: 0
  walking: 1
  running: 2
  sawing: 3
num_variables: 3

encoding:
  input_dim: 1
  hidden_dim: 32
  latent_dim: 16
  batch_size: 137
  lr: 0.01
  gamma: 0.999
  epochs: 3000
  m: 1.0
  save_dir: models/epilepsy/encoding/

single_variable_prototypes:
  num_prototypes:
    - 4
    - 4
    - 4
  num_layers: 2
  batch_size: 137
  lr: 0.01
  gamma: 0.999
  epochs: 1000
  l1: 1.0
  l2: 1.0
  l3: 1.0
  l4: 1.0
  d_min: 1.0
  save_dir: models/epilepsy/single_variable_prototypes/

multivariable_prototypes:
  num_layers: 1
  batch_size: 137
  lr: 0.01
  gamma: 0.999
  epochs: 1000
  l1: 1.0
  l2: 100.0
  l3: 1.0
  l4: 1.0
  d_min: 1.0
  save_dir: models/epilepsy/multivariable_prototypes/
