classes:
    - Epilepsy
    - Walking
    - Running
    - Sawing
class_to_index:
  epilepsy: 0
  walking: 1
  running: 2
  sawing: 3
num_variables: 3

encoding:
  input_dim: 1
  hidden_dim: 64
  latent_dim: 32
  batch_size: 137
  lr: 0.01
  gamma: 0.999
  epochs: 1000
  m: 1.0
  save_dir: models/epilepsy/encoding/